const EnumActions = Object.freeze({
    "APPLICATION_USER_LOGIN": "APPLICATION_USER_LOGIN",
    "APPLICATION_USER_LOGOUT": "APPLICATION_USER_LOGOUT",
    "APPLICATION_LANGUAGE_CHANGE": "APPLICATION_LANGUAGE_CHANGE",
    "LANDING_LOADING_CHANGE": "LANDING_LOADING_CHANGE",
    "LANDING_DATA_CHANGE": "LANDING_DATA_CHANGE"
});

export default EnumActions;